version: "3.3"

services:

  application:
    container_name: application
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 9090:9090
    env_file:
      - '../.env'
