name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - master
    - main

jobs:
  go:
    name: Golang Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Golang Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
